name: Blue Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend
        run: docker build -t backend:green ./backend

      - name: Build Frontend
        run: docker build -t frontend:green ./frontend

      - name: Deploy Backend Green
        run: kubectl apply -f kubernetes/backend/backend-green-deployment.yaml

      - name: Deploy Frontend Green
        run: kubectl apply -f kubernetes/frontend/frontend-green-deployment.yaml
